CREATE DATABASE tienda

USE tienda;

CREATE TABLE usuarios (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    telefono CHAR(9) NOT NULL,
    password varchar(255) NOT NULL,
    imagen VARCHAR(100),
    rol VARCHAR(20) NOT NULL DEFAULT 'cliente',
    estado TINYINT(1) NOT NULL DEFAULT 0,
    token VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

INSERT INTO usuarios (nombres, apellidos, correo, telefono, password) VALUES
    ('Juancito', 'Perez', 'prueba@gmail.com', '123456789', 'password123')

CREATE TABLE categorias (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    usuario_id INT UNSIGNED NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    orden INT UNSIGNED NOT NULL,
    estado TINYINT(1) NOT NULL DEFAULT 0,
    descripcion TEXT,
    imagen VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_categoria
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)    
    ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE productos (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    usuario_id INT UNSIGNED NOT NULL,
    categoria_id INT UNSIGNED NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    sku VARCHAR(100) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    stock INT UNSIGNED NOT NULL,
    estado TINYINT(1) NOT NULL DEFAULT 0,
    descripcion TEXT NOT NULL,
    imagen VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_producto
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_categoria_producto
    FOREIGN KEY (categoria_id) REFERENCES categorias(id)
    ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE producto_galeria (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    producto_id INT UNSIGNED NOT NULL,
    imagen VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_producto_galeria
    FOREIGN KEY (producto_id) REFERENCES productos(id)
    ON DELETE CASCADE ON UPDATE CASCADE
)