CREATE DATABASE tienda

USE tienda;

CREATE TABLE usuarios (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    telefono CHAR(9) NOT NULL,
    password varchar(255) NOT NULL,
    imagen VARCHAR(100),
    rol VARCHAR(20) NOT NULL DEFAULT 'cliente',
    estado TINYINT(1) NOT NULL DEFAULT 0,
    token VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)